### PR TITLE
Rails 5 support

### PR DESCRIPTION
**Pull request by daveallie**
Gem defines a `before_filter` in the controller, which is no longer supported by Rails 5.

Use `before_action` instead.

### CODE REVIEW

**Comment by NotDaveLane** [comment]
Is there any update on this? It'd be great if this were accepted into master. I just hit a quirk where Rails 5.1 ran fine locally but died in a production env due to this.

**Comment by saravana-cb** [comment]
We have asked our collaborators to take care of pull req. It ll be merged soon.

**Comment by sai92messy** [comment]
Looks good to me. @Thirumal-Sakthivel please review and merge this PR.

**Comment by Thirumal-Sakthivel** [comment]
Merged.

**Comment by daveallie** [comment]
As far as I'm aware the `chargebee_rails` gem which we use is actually maintained over here: https://github.com/spritlesoftware/chargebee-rails-subscriptions

Fingers crossed my PR gets merged over there too. https://github.com/spritlesoftware/chargebee-rails-subscriptions/pull/8

**Pull request merged**
